# The URL the site will be built for
base_url    = "https://www.digidopa.nl/"
author      = "DigiDOPA"
title       = "DigiDOPA"
description = "Dagelijkse registratie van medicatie effecten voor Parkinsonpatiënten"

# Project settings
compile_sass = false
build_search_index = false
generate_sitemap = true
minify_html = true
generate_robots_txt = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

[extra]
# Custom variables
email = "info@digidopa.nl"
phone = "078 68 11 500"